[window]
decorations = "buttonless"

[window.padding]
x = 10
y = 15

[colors.primary]
background = "#001D2E"

[font]
size = 14

[font.bold]
family = "MesloLGL Nerd Font"

[font.italic]
family = "MesloLGL Nerd Font"

[font.normal]
family = "MesloLGL Nerd Font"

[scrolling]
history = 1000
multiplier = 1

