# Path for oh-my-posh theme
eval "$(oh-my-posh init zsh --config $HOME/.config/oh-my-posh/zhunio.json)"
eval "$(fzf --zsh)"
# Path for nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
# aliases
alias python="python3"

